### ISSUE TITLE
When will we see the code?

### ISSUE THREAD

**Issue by mf46** [JarrentWu1031/SingleInsert#1]
Hi! I believe you guys are doing awsome job!  When are you planning to public your code ?

**Comment by JarrentWu1031** [comment]
Thanks! The code will be released in the coming weeks.

**Comment by chenjun0210** [comment]
awsome job！when

**Comment by nullarch** [comment]
wow! nice work thank you @JarrentWu1031

**Comment by nullarch** [comment]
is there any news for release code? I m waiting for release !

**Comment by zimenglan-sysu-512** [comment]
still have plan to release the training code and the trained models?

**Comment by nullarch** [comment]
This is no code repo. I think there is no plan to release code. Don't wait

**Comment by JarrentWu1031** [comment]
Due to some complex issues, the code has only been open-sourced up now. Sorry for the delay!
